rules:
  default:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - ci/jenkins/pr_tests
          - mergify/allow
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
      enforce_admins: true
